import { ICategory } from "../types";

export const KORVONAL2_NAME = "Körvonal 2" as const;

export const KORVONAL2: ICategory = {
  name: KORVONAL2_NAME as string,
  questions: [
    "Ha egy külső tulajdonságodat megváltoztathatnád, melyik lenne az?",
    "Milyen tanácsot adnál valakinek gyerekvállalás előtt?",
    "Melyik az a képességed, amit nem tudtál eddig kamatoztatni?",
    "Ha egy új dolgot megtanulhatnál, mi lenne az?",
    "Mi az elismerésre méltóbb? Ha valaki kitalálja, vagy valaki megcsinálja?",
    "Szerinted mi történik velünk a halál után?",
    "Mi az az illegális dolog, amit elkövetnél, ha tudnád, hogy megúszod büntetés nélkül?",
    "Mikor vesztetted el utoljára a türelmed és miért?",
    "Hogyan vígasztalnál valakit, akit épp elhagyok?",
    "Mi az, amit nagyon nehezen tolerálsz?",
    "Egy szóval jellemezd magad.",
    'Érezted már úgy valaha magad, hogy "átverted a rendszert"?',
    "Voltál olyan szituációban, amikor úgy érezted nevetséges vagy?",
    "Ki tud a legjobban megnevettetni?",
    "Hiszel a vonzás erejében?",
    "Mi volt a legnagyobb hülyeség, amit valamelyik barátod csinált?",
    "Melyik idegen nyelvet szeretnéd beszélni?",
    "Hogy váltasz témát, ha már nagyon unod amiről szó van?",
    "Mi volt a legtöbb pénz, amit ajándékra költöttél?",
    "Melyik volt életed legmegalázóbb pillanata?",
    "Meséld el életed legrosszabb nyaralását.",
    "Melyik szokásoddal szeretnél felhagyni?",
    "Melyik a legjobb emléked egy idegennel?",
    "Miben szeretnél tehetséges lenni?",
    "Mi az, amin akár naponta fel tudod húzni magad?",
    "Melyik fizikai tulajdonságodnak örülsz a legjobban?",
    "Hogy reagálsz, amikor tudod, hogy valamit rosszul csináltál?",
    "Szerinted a személyiségünkkel születünk, vagy útközben alakul ki?",
    "Ki volt rád a legnagyobb hatással életed során?",
    "Mibe érdemes manapság pénzt fektetni szerinted?",
    "Van olyan dolog, amit egyszerűen nem tudsz megjegyezni?",
    "Mi volt élted legnagyobb fogása?",
    "Hogyan és hol telne álmaid szülinapja?",
    "Ha egy másik nemzet ételét ehetnéd életed végéig, melyik lenne az?",
    "Mi a legfontosabb dolog az életben?",
    "Melyik tárgy a leghasznosabb a lakásodban?",
    "Van valamilyen furcsa szokásod ételpárosítás terén?",
    "Ha egy hétre szakmát válthatnál, mi lenne az?",
    "Milyen tanácsot adnál valakinek házasságkötés előtt?",
    "Melyik volt életed legmeghatározóbb döntése?",
  ],
};
