import { ICategory } from '../types';

export const KORVONAL_NAME = "Körvonal" as const;

export const KORVONAL: ICategory = {
  name: KORVONAL_NAME as string,
  questions: [
    "Ha egyetlen egy dolgot változtathatnál meg a múltadban, mi lenne az?",
    "Mi volt a legkellemetlenebb dolog, amit mások előtt csináltál?",
    "Mit fogsz másképp csinálni, mint a szüleid?",
    "Ki az akinek minden esetben adsz a véleményére?",
    "Mi az amit elkezdtél, de sosem fejezted be, és miért?",
    "Mi a legviccesebb emléked?",
    "Életed legrosszabb napja.",
    "Híres lennél, vagy gazdag?",
    "Mikor sírtál utoljára, és miért?",
    "A legnagyobb lecke, amit ebben az évben megtanultál?",
    "Hol találsz békére?",
    "Mi az, amire a kelleténél jóval több időt szánsz?",
    "Ha 24 óra lenne hátra az életedből, mivel töltenéd?",
    "Mi hiányzik az életedből?",
    "Ha az egész világ hallana egy mondat erejéig, mit mondanál?",
    "Min nevettél úgy utoljára, hogy folyt a könnyed?",
    "Szerinted mi miatt lehet jobb nőnek lenni?",
    "Egy napra kinek a bőrébe bújnál?",
    "Melyik volt a legérdekesebb hely, ahol életedben jártál?",
    "Mi lehet a legnehezebb a veled való közös életben?",
    "A legfontosabb lecke amit a szüleidtől tanultál?",
    "Milyen számodra a tökéletes vasárnap?",
    "Mi okozta a legnagyobb bánatot az életedben?",
    "Ha nyernél a lottón, folytatnád a munkát amit most csinálsz?",
    "Kinek az életét tartod irigylésre méltónak az ismerőseid közül? Miért?",
    "Ha bármelyik már nem élő rokonodat visszahoznád, ki lenne az?",
    "Valami, amit még sosem mondtál el senkinek?",
    "Mikor érezted magad igazán szerencsésnek?",
    "Kedvenc idézeted.",
    "Ha király lehetnél, mi lenne az első dolog, amin változtatnál az országodban?",
    "Mi az a munka, amit soha nem csinálnál akármennyi pénzt ajánlanának érte?",
    "Milyen címet adnál a jelenlegi fejezetednek az életedben?",
    "Egy mondat amivel a legjobban megbántottak életed során.",
    "Mi az amit nehezen ismersz be magaddal kapcsolatban?",
    "Ha kapnál egy repülőjegyet bárhova, hova mennél?",
    "Szeretnéd ha a gyerekeid rád hasonlítanának? Ha igen, miben?",
    "Mi az a hazugság, amit a legtöbbször mondtál életed során?",
    "Kinek kellene köszönetet mondanod az életedben és miért?",
    "Valami amit másért tettél és a mai napig jóérzéssel tölt el.",
    "Mire vagy a legbüszkébb?",
    "Kettő embert vihetsz magaddal egy lakatlan szigetre. Kik azok?",
    "Az érzés ami a leggyakrabban a hatalmába kerít.",
    "Ha lehetne egy szuperképességed, mit választanál?",
    "Mi a legnagyobb vágyad, amiről még senkinek sem meséltél?",
    "A legjobb tulajdonság egy emberben?",
    "Szégyelted magad valaha mások helyett? Mikor és miért?",
    "Ha el kellene költöznöd egy másik országba, hova mennél?",
    "Milyennek képzeled a tökéletes életet?",
    "Melyik emlékedet törölnéd egy életre?",
    "Mit kellene tudnia rólad az embereknek, amit jelenleg nem tudnak?",
    "Ha utazhatnál az időben, hova mennél?",
    "Mi az, amit soha nem tudnál megbocsátani?",
    "Egy kaland, amit nagyon irigyeltél egyszer valakitől.",
    "Mi a legkorábbi gyerekkori emléked?",
    "Mire van legnagyobb szükséged jelenleg?",
    "Egy tárgy, ami nélkül nem tudnál élni.",
    "Ha megkérdeznék a barátaidat a legrosszabb tulajdonságodról, szerinted mit válaszolnának?",
    "Szerinted mi az első benyomása rólad az embereknek?",
    "Mi az, amitől félsz is, de ki is próbálnád?",
    "Ha egy napra kisgyerek lehetnél, mit élveznél benne a legjobban?",
  ],
};
