import { ICategory } from "../types";

export const PARBESZED_NAME = "Párbeszéd" as const;

export const PARBESZED: ICategory = {
  name: PARBESZED_NAME as string,
  questions: [
    "Milyen helyzetekben vagy magabiztos?",
    "Milyen félelmedet győzted le eddig életed során?",
    "Milyen szokások vagy rutinok segítenek neked a kreativitás és az inspiráció fenntartásában?",
    "Mi volt az a lecke, amiből a legtöbbet tanultál?",
    "Milyen erősségekkel rendelkezel, amelyeket gyakran alulértékelnek?",
    "Mi a legnagyobb elvárásod magaddal szemben?",
    "Milyen módon kezeled a stresszt?",
    "Milyen környezeti tényezők hatnak jótékonyan a jóllétedre és a kreativitásodra?",
    "Milyen új dolgot szeretnél megtanulni?",
    "Milyen tevékenységek vagy helyzetek adnak neked igazi örömöt és boldogságot?",
    "Milyen viselkedést és tulajdonságokat értékelsz egy barátban vagy egy párkapcsolatban?",
    "Milyen céljaid vannak az idei évre?",
    "Ha a mai nap lenne életed utolsó napja, mit bánnál a legjobban, hogy nem tettél meg?",
    "Mi a legnagyobb motivációd?",
    "Mikor voltál magadra igazán büszke?",
    "Sorolj fel három dolgot, amiért ma hálás vagy?",
    "Melyik a legkedvesebb emléked gyerekkorodból?",
    "Ha találkoznál a 10 évvel későbbi önmagaddal, mit kérdeznél tőle?",
    "Milyen hivatás tűnik a leginkább vonzónak és jelentőségteljesnek számodra?",
    "Milyen hatással vannak az emberi kapcsolataid az életedre?",
    "Mondj egy dolgot amit egy éven belül szeretnél megváltoztatni az életedben.",
    "Mit vársz az életedtől a következő 10 évben?",
    "Ha találkoznál a 10 évvel ezelőtti önmagaddal, milyen tanácsot adnál neki?",
    "Mi volt életed során a legjelentősebb eredményed, és miért tartod fontosnak?",
    "Mit jelent neked a siker?",
    "Mondj magadról három pozitív külső és belső tulajdonságot.",
    "Milyen hatékony stratégiáid vannak az érzelmi egyensúly fenntartására?",
    "Mi az életcélod, és milyen lépéseket teszel annak érdekében, hogy elérd?",
    "Mire vágytál a legjobban életed során, amit végül megkaptál?",
    "Mit teszel a testi egészségedért?",
    "Milyen helyzetek és helyek okoznak számodra szorongást vagy kényelmetlenséget? Mit gondolsz, mi lehet ennek a hátterében?",
    "Mit teszel a lelki egészségedért?",
    "Van-e olyan terület, ahol fejleszthetnéd a kommunikációs készségedet?",
    "Nevezz meg néhány dolgot, amiben szeretnél fejlődni.",
    "Mit gondolsz, mik az erősségeid?",
    "Kik azok az emberek az életedben, akik inspirálnak és bátorítanak a fejlődésben?",
    "Mire vágytál a legjobban életed során, amit eddig nem kaptál meg?",
    "Melyik a legfájóbb emléked a gyerekkorodból?",
    "Ha egy emberrel találkozhatnál a múltadból, ki lenne az, és mit mondanál neki?",
    "Mi tud a legjobban megnyugtatni?",
  ],
};
